### ISSUE TITLE
type,DataException, message,no data, code,800 and coverSize

### ISSUE THREAD

**Issue by z3huti** [d-fi/releases#23]
√ Enter URL or search: ... https://www.deezer.com/us/track/912254892
ℹ info Proceeding download of 1 tracks. Be patient.
✔ error Levitating
  → type,DataException, message,no data, code,800

this error comes only with some URLs / tracks

in version 1.3.10 works ok

**********

changing coverSize in d-fi.config.json  does nothing, its always 500x500 for all formats

**Comment by sayem314** [comment]
Fixed on beta 8. Thanks for reporting.

**Comment by z3huti** [comment]
> Fixed on beta 8. Thanks for reporting.

changing coverSize in d-fi.config.json still does nothing, its always 500x500

**Comment by sayem314** [comment]
Yes sorry. Fixed now on beta 9. Thanks again :)
